insert into receta (id, nota, resultado, id_proceso) values (1, 'ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere', 5, 3);
insert into receta (id, nota, resultado, id_proceso) values (2, 'sapien varius ut blandit non interdum in ante vestibulum ante ipsum', 4, 3);
insert into receta (id, nota, resultado, id_proceso) values (3, 'nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam', 1, 1);
insert into receta (id, nota, resultado, id_proceso) values (4, 'justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id', 5, 2);
insert into receta (id, nota, resultado, id_proceso) values (5, 'sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at', 5, 1);
insert into receta (id, nota, resultado, id_proceso) values (6, 'massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien', 1, 3);
insert into receta (id, nota, resultado, id_proceso) values (7, 'phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at', 2, 1);
insert into receta (id, nota, resultado, id_proceso) values (8, 'justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi', 3, 2);
insert into receta (id, nota, resultado, id_proceso) values (9, 'amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem', 2, 1);
insert into receta (id, nota, resultado, id_proceso) values (10, 'condimentum curabitur in libero ut massa volutpat convallis morbi odio odio', 5, 2);
insert into receta (id, nota, resultado, id_proceso) values (11, 'vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus', 5, 1);
insert into receta (id, nota, resultado, id_proceso) values (12, 'sit amet eros suspendisse accumsan tortor quis turpis sed ante', 3, 3);
insert into receta (id, nota, resultado, id_proceso) values (13, 'mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes', 2, 1);
insert into receta (id, nota, resultado, id_proceso) values (14, 'non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in', 2, 3);
insert into receta (id, nota, resultado, id_proceso) values (15, 'non velit nec nisi vulputate nonummy maecenas tincidunt lacus at', 3, 2);
insert into receta (id, nota, resultado, id_proceso) values (16, 'quam pede lobortis ligula sit amet eleifend pede libero quis', 2, 2);
insert into receta (id, nota, resultado, id_proceso) values (17, 'nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in', 1, 1);
insert into receta (id, nota, resultado, id_proceso) values (18, 'aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et', 5, 1);
insert into receta (id, nota, resultado, id_proceso) values (19, 'eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in', 4, 3);
insert into receta (id, nota, resultado, id_proceso) values (20, 'turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus', 2, 1);
